export const MODAL_OPEN = 'MODAL_OPEN'
export const MODAL_CLOSE = 'MODAL_CLOSE'

export const GET_STOCKS_LOADING = 'GET_STOCKS_LOADING'
export const GET_STOCKS_SUCCESS = 'GET_STOCKS_SUCCESS'
export const GET_STOCKS_ERROR = 'GET_STOCKS_ERROR'
export const GET_STOCKS_TOTAL_VALUE = 'GET_STOCKS_TOTAL_VALUE'
export const BUY_STOCK_SUCCESS = 'BUY_STOCK_SUCCESS'
export const BUY_STOCK_ERROR = 'BUY_STOCK_ERROR'

export const ADD_TO_CART = 'ADD_TO_CART'
export const REMOVE_FROM_CART = 'REMOVE_FROM_CART'
export const CLEAR_CART = 'CLEAR_CART'
export const GET_CART_TOTAL = 'GET_CART_TOTAL'

export const GET_USER_LOADING = 'GET_USER_LOADING'
export const GET_USER_SUCCESS = 'GET_USER_SUCCESS'
export const GET_USER_ERROR = 'GET_USER_ERROR'
export const GET_USER_BALANCE = 'GET_USER_BALANCE'
